lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    # user_identity_field: email # Champs d'identification unique utilisé par le token
    token_ttl: 60 # Durée de vie du token en secondes